networks:
  network:
    driver: bridge
    
volumes:
  postgres_data:
  sql_data:

services:
  
  nginx:
    container_name: ProjectStoreNginx
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    depends_on:
      - api
        
  angular:
    container_name: ProjectStoreAngular
    restart: always
    build:
      context: .
      dockerfile: Presentation/Example.Angular/Dockerfile
      
#    develop:
#      watch:
#        - action: sync
#          path: .Presentation/Example.Angular/src
#          target: /app/src
#          ignore:
#            - node_modules/
#        - action: rebuild
#          path: package.json
          
    ports:
      - "4201:4200"
    depends_on:
      - api
    networks:
      - network
  
  api:
    container_name: ProjectStoreAPI
    image: projectstore.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: ProjectStore.API/Dockerfile
    ports:
      - "5015:5001"
    networks:
      - network
    depends_on:
      - db
      - mssql
  db:
    image: postgres:latest
    container_name: ProjectStorePostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ProjectStore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
        
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "HlxTm2fcFE54JA1I_Yp5"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - network
    

