networks:
  network:
    driver: bridge
    
volumes:
  postgres_data:

services:
  
  nginx:
    container_name: ProjectStoreNginx
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    depends_on:
      - api
  
  api:
    container_name: ProjectStoreAPI
    image: projectstore.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: ProjectStore.API/Dockerfile
    ports:
      - "5015:5001"
    networks:
      - network
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: ProjectStorePostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ProjectStore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
    

