name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Delete old repository from VPS, clone new repo, deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/artik3314/project
            git clone https://github.com/artemovsergey/React.git /home/artik3314/project/
            chmod +x /home/artik3314/project/scripts/vps.sh
            /home/artik3314/project/scripts/vps.sh