name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  
jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.33'

      - name: Install dependencies and run tests
        run: |
          dotnet restore
          dotnet test --verbosity normal

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Delete old repository from VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/artik3314/project

      - name: Сlone new repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            git clone https://github.com/artemovsergey/ProjectStore.git /home/artik3314/project/
            
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/artik3314/project/scripts/vps.sh
            /home/artik3314/project/scripts/vps.sh